name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# allow pushing version bumps and container images
permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # ---- 2a: bump PATCH automatically to 1.0.<run_number> ----
      - name: Set Maven version to 1.0.${{ github.run_number }}
        run: |
          mvn -q versions:set -DnewVersion=1.0.${{ github.run_number }}
          mvn -q versions:commit
          echo "Effective version:" && mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # ---- 2c: login to GHCR and push image ----
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:1.0.${{ github.run_number }}
            ${{ env.IMAGE_NAME }}:latest

      # --- Create Git tag and GitHub Release with the jar attached ---
      - name: Create git tag v${{ env.VERSION }}
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          generate_release_notes: true
          files: |
            target/my-app-*.jar
